const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const sql=fs.readFileSync(path.join(__dirname,'../sql/auth_supabase_migration.sql'),'utf8');
const ids=[...new Set([...sql.matchAll(/'([0-9a-f-]{36})'/g)].map(x=>x[1]))];
test('migration preserves cohort/history; Auth sync, roles, approval, sessions, audit and assignment guards',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;
 CREATE SCHEMA auth;
 CREATE TABLE auth.users(id uuid PRIMARY KEY,phone text,phone_confirmed_at timestamptz,raw_user_meta_data jsonb DEFAULT '{}',phone_change text DEFAULT '',phone_change_token text DEFAULT '');
 CREATE TABLE auth.sessions(id uuid PRIMARY KEY,user_id uuid,created_at timestamptz DEFAULT now());
 CREATE TYPE user_role AS ENUM('farmer','distributor','retailer','delivery_personnel');
 CREATE TABLE users(id uuid PRIMARY KEY,full_name text NOT NULL,phone text UNIQUE NOT NULL,role user_role NOT NULL,password_hash text NOT NULL,
 farm_location text,store_location text,service_area text,latitude numeric,longitude numeric,created_at timestamptz DEFAULT now());
 CREATE TABLE orders(id uuid PRIMARY KEY,retailer_id uuid REFERENCES users(id),delivery_personnel_id uuid REFERENCES users(id));
 CREATE TABLE deliveries(id uuid,delivery_personnel_id uuid REFERENCES users(id));
 CREATE TABLE pickup_requests(id uuid,farmer_id uuid REFERENCES users(id),delivery_personnel_id uuid REFERENCES users(id));
 CREATE TABLE harvests(id uuid,farmer_id uuid REFERENCES users(id));
 CREATE TABLE products(id uuid);CREATE TABLE order_items(id uuid);CREATE TABLE payments(id uuid);CREATE TABLE messages(id uuid);CREATE TABLE notifications(id uuid);CREATE TABLE delivery_addresses(id uuid);CREATE TABLE delivery_tracking(id uuid);
 GRANT ALL ON ALL TABLES IN SCHEMA public TO anon,authenticated;
 `);
 for(let i=0;i<ids.length;i++)await db.query('INSERT INTO users(id,full_name,phone,role,password_hash) VALUES($1,$2,$3,$4,$5)',[ids[i],'Legacy','0917'+String(i).padStart(7,'0'),i===0?'distributor':i===1?'delivery_personnel':'retailer','legacy-hash']);
 await db.query('INSERT INTO orders VALUES($1,$2,$3)',['11111111-1111-1111-1111-111111111111',ids[2],ids[1]]);
 await db.exec(sql);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM users WHERE legacy_access AND account_status=\'active\'')).rows[0].n,12);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM orders')).rows[0].n,1);
 assert.equal((await db.query('SELECT count(*)::int AS n FROM users WHERE phone_verified_at IS NOT NULL')).rows[0].n,0);
 for(let i=0;i<2;i++)await db.query('INSERT INTO auth.users(id,phone,phone_confirmed_at,raw_user_meta_data) VALUES($1,$2,now(),$3)',[ids[i],'63917'+String(i).padStart(7,'0'),{}]);
 const session='22222222-2222-2222-2222-222222222222';
 await db.query('INSERT INTO auth.sessions VALUES($1,$2,now())',[session,ids[0]]);
 const applicant='33333333-3333-3333-3333-333333333333';
 await assert.rejects(db.query('INSERT INTO auth.users(id,phone,raw_user_meta_data) VALUES($1,$2,$3)',[applicant,'639191234567',{role:'distributor',full_name:'Attacker',account_status:'active'}]),/role not allowed/);
 await db.query('INSERT INTO auth.users(id,phone,raw_user_meta_data) VALUES($1,$2,$3)',[applicant,'639191234567',{role:'farmer',full_name:'New',account_status:'active'}]);
 const state=async id=>(await db.query('SELECT * FROM users WHERE id=$1',[id])).rows[0];
 assert.equal((await state(applicant)).account_status,'unverified');
 await db.query('UPDATE auth.users SET phone_confirmed_at=now() WHERE id=$1',[applicant]);
 assert.equal((await state(applicant)).account_status,'pending_approval');
 const transition=(id,action,reason,version=0)=>db.query('SELECT vt_admin_transition($1,$2,$3,$4,$5,$6)',[ids[0],session,id,action,reason,version]);
 await assert.rejects(transition(applicant,'DECLINED',''),/Reason required/);
 await transition(applicant,'APPROVED',null);
 await assert.rejects(transition(applicant,'APPROVED',null),/Stale/);
 assert.equal((await state(applicant)).account_status,'active');
 const previous=await state(applicant);
 await assert.rejects(db.query('UPDATE auth.users SET phone=$1 WHERE id=$2',['639201234567',applicant]),/Verified phone change/);
 await db.query("UPDATE auth.users SET phone_change=$1,phone_change_token='auth-managed-token' WHERE id=$2",['639201234567',applicant]);
 assert.equal((await state(applicant)).phone,previous.phone);
 await db.query("UPDATE auth.users SET phone=$1,phone_change='',phone_change_token='' WHERE id=$2",['639201234567',applicant]);
 const changed=await state(applicant);
 for(const key of ['id','role','account_status','approved_by','status_version'])assert.equal(changed[key],previous[key]);
 assert.equal(changed.phone,'+639201234567');
 assert.equal((await db.query("SELECT count(*)::int AS n FROM account_audit WHERE action='PHONE_NUMBER_CHANGED'")).rows[0].n,1);
 await db.query("UPDATE auth.users SET phone_change=$1,phone_change_token='auth-managed-token' WHERE id=$2",['639170000000',applicant]);
 await assert.rejects(db.query("UPDATE auth.users SET phone=$1,phone_change='',phone_change_token='' WHERE id=$2",['639170000000',applicant]),/duplicate key/);
 assert.equal((await state(applicant)).phone,'+639201234567');
 await assert.rejects(transition(ids[1],'DISABLED',''),/Reason required/);
 const oldSession='44444444-4444-4444-4444-444444444444';
 await db.query("INSERT INTO auth.sessions VALUES($1,$2,now()-interval '1 day')",[oldSession,ids[1]]);
 await transition(ids[1],'DISABLED','Unavailable');
 assert.equal((await db.query('SELECT vt_account_context($1,$2) AS context',[ids[1],oldSession])).rows[0].context,null);
 await assert.rejects(db.query('INSERT INTO deliveries VALUES($1,$2)',['55555555-5555-5555-5555-555555555555',ids[1]]),/active participant/);
 assert.equal((await db.query('SELECT delivery_personnel_id FROM orders')).rows[0].delivery_personnel_id,ids[1]);
 await transition(ids[1],'REACTIVATED',null,1);
 assert.equal((await db.query('SELECT vt_account_context($1,$2) AS context',[ids[1],oldSession])).rows[0].context,null);
 await db.exec('SET ROLE authenticated');
 for(const statement of ['SELECT * FROM orders','UPDATE users SET account_status=\'active\'','SELECT vt_admin_transition(null,null,null,null,null,0)','INSERT INTO account_audit(target_id) VALUES(null)'])await assert.rejects(db.exec(statement),/permission denied/);
 await db.exec('RESET ROLE');
 }finally{await db.close();}
});
